### ISSUE TITLE
nonce() Issues

### ISSUE THREAD

**Issue by jacobscarter** [dutu/poloniex-api-node#10]
I have had several API calls rejected because of a `nonce` with a smaller number than the previous.  Is there a reason you went with the `npm nonce` library instead of just using `new Date().getTime()` ?

Example error I am getting:

```
{
    error: 'Nonce must be greater than 149394554342600. You provided 149394554342500.'
}
```

**Comment by jacobscarter** [comment]
Also thanks for this package, I appreciate you :)

**Comment by dutu** [comment]
Generate a new API key and make sure you don't use it for other app. 

`nonce` package is also based on Unix time and I've preferred using this package in order to save make use of already written code.
