### ISSUE TITLE
returnLendingHistory problem with no value returned

### ISSUE THREAD

**Issue by yendor987** [dutu/poloniex-api-node#13]
Hello everyone,

I'm trying to make the function returnLendingHistory work from the lib poloniex.js
I've attached the file concerned, I do not have any error message so I assume that the "start" and "end" parameter are correctly defined
The only thing is that I do not get any value returned when trying this example:

$node myExample1.js
$[ ]

[myExample1.js.txt](https://github.com/dutu/poloniex-api-node/files/999863/myExample1.js.txt)

Does anyone have an example that is working?
Thank you

yendor987

**Comment by dutu** [comment]
timestamp should be in seconds, rather than milliseconds. 

Here is your example updated:
```
let start = new Date("2017-05-01").getTime() / 1000;
let end = new Date("2017-05-10").getTime() / 1000;

poloniex.returnLendingHistory(start, end, null, function (err, lendingHist) {
    if (err) {
        console.log(err.message);
    } else {
        console.log(lendingHist);
    }
});
```

**Comment by yendor987** [comment]
Thank you dutu, it is working now
