### ISSUE TITLE
Any plans for implementing the streaming/push API?

### ISSUE THREAD

**Issue by meteorpublish** [dutu/poloniex-api-node#15]

**Comment by dutu** [comment]
Poloniex is planning to release a new version of push API and I'm planing to implement the new one when released (hopefully shortly).

**Note:** Currently there are many issues with Poloniex WAMP implementation, such as dropped/delayed events and the entire string of events lagging behind sometimes to up to 2 minutes (observed for orderbook events).

Here is a response from Poloniex support:

> "The rate of dropped or delayed events with the WAMP API could depend on many factors but the gist of the issue is that the WAMP router isn't scalable for our needs, we will be replacing this with the new websocket API as soon as possible. I believe that only the documentation is waiting to be finalized and we should see this released soon"

**Comment by meteorpublish** [comment]
~4 months later, any updates from Poloniex?

**Comment by dutu** [comment]
I've requested an update from Poloniex and this is all I've got:

> We will look into this and get back to you as soon as possible.
> Our sincere apologies for the inconvenience, and thank you for your patience in the mean time.

**Comment by dutu** [comment]
WebSocket (push) API is implemented in version 1.5.0.
This is based on the WAMP API (not the new WebSocket API Poloniex has promised to release)

**Comment by meteorpublish** [comment]
Nice, thank you! How stable does it seem to be? See https://github.com/coinbase/gdax-node/issues/104 for comparison.

**Comment by dutu** [comment]
I didn't have issue with session being disconnecting,
In anycase the module implements reconnection https://github.com/dutu/poloniex-api-node/blob/master/lib/poloniex.js#L506-L513

The issues I had were related to delayed messages for order book events and the need to resync using REST API. I'm not sure if Poloniex has remedied the situation as I'm haven't been used that specific application for the past couple of months.

**Comment by dutu** [comment]
new WebSocket API (v2) has been implemented as well, which is much faster and reliable
