### ISSUE TITLE
Massive ESOCKETTIMEDOUT erors even with large time outs

### ISSUE THREAD

**Issue by JustWantToAsk1** [dutu/poloniex-api-node#17]
I know this is most likely not on your side but I have to ask because I am not seeing this anywhere.

It looks like today, 6/6/2017, and yesterday during the day 6/5//2017 there was a massive problem with the poloniex servers. (The servers were fine last night)

Nearly all requests returned with a ESOCKETTIMEDOUT error, and after a couple or a few of these, results in a 2 minute ban.

I am handling the bans gracefully so that the next call waits the ban time and I add 10 seconds to all my calls. (Example: I run the program every 30 seconds which should be enough. If there is a ban, I than run my program at 40 seconds. This got up to 200 seconds so something is massively wrong with poloniex servers)

I just am trying to think of all edge cases and wanted to make sure it is not poloniex-api-node which is failing but the poloniex servers as I think. 

Also, is anyone else experiencing this or am I going crazy over here? It's always been a little shaky but this time is different.

Thanks.

**Comment by dutu** [comment]
Lately, Poloniex has changed their way of throttling and limiting API calls to prevent DDoS attacks.
It has been seen that after a couple of ESOCKETTIMEDOUT occur, a temporary ban on the IP address is imposed resulting in errors code 429.

Increasing the timeout to 60 seconds alleviates the problem. (Poloniex recommends a timeout of 130 seconds, but setting it to at least 60 seconds works).

The timeout can be set by passing the parameter `{ socketTimeout: 130000 }` in the constructor.

**Comment by JustWantToAsk1** [comment]
Thanks for the response dutu.

Yeah that will help alleviate the bans. I will add that code.

The situation I described is happening again this morning for the 3rd time.

It starts around 6:00am EST and ends around 5:30pm EST. Within that time frame hardly any requests are able to send through (I got a couple of sell requests through). The odd thing is, that there wasn't high traffic on the poloniex website and I could trade on there with no problem. Just the api calls weren't getting through.

Are you seeing this by any chance? Something is wrong on there end big time. It has to be something with the servers. My wild guess is that some sort of server switch over is taking place and this time slot gets the bad server. Very odd.

**Comment by dutu** [comment]
Note that the error code 429 and the temporary IP ban is imposed by the Poloniex's Coudflare and it'll happen even if the Poloniex is not under heavy load.

You can increasing the timeout to get rid of ESOCKETTIMEDOUT and it'll minimizing the occurrence of error code 429 and IP ban.

**Comment by JustWantToAsk1** [comment]
Dutu you are a life saver. My program is running really smooth with your fix.

I wonder if there is some additional stuff that happens behind the scenes with a 2 minute ban. I don't think it is just a 2 minute ban. They must put your IP on some sort of watch list. It might be worth keeping an eye on.

I can manually change my IP by re starting my modem but it is worth watching.

Thanks for the help. This wrapper library is great.
