### ISSUE TITLE
Poloniex error 403: Forbidden

### ISSUE THREAD

**Issue by Geo-Joy** [dutu/poloniex-api-node#20]
getting Poloniex error 403: Forbidden on all api

**Comment by dutu** [comment]
@Geo-Joy, the error code and the error description are returned by Poloniex server. 
Check you API key permission and API key's IP access restriction, if issue persists, I suggest you open a ticket with Poloniex support.

**Comment by Geo-Joy** [comment]
@dutu does anyone using this repo facing the same issue?

Things I did after @dutu 's reply
1) Enable 2FA
2) Created New API key - same error exists. (both with new key and the previously created keys)

3) Disables 2FA
4)Created New API key - same error exists. (both with new key and the previously created 2FA and older keys.)

5) Wrote a ticket to POLONIEX support (awaiting response).

**Comment by g666nz** [comment]
Received the same error. Sent then a ticket. I think there was a problem with my code because initially i was receiving there entire websites front end source code and then after that I started receiving the 403 error. I've submitted a ticket, let's see.

**Comment by Geo-Joy** [comment]
@g666nz . The entire website code you mentioned is POLONIEX's captcha code web page, which shows up on all public apis.

**Comment by dutu** [comment]
@Geo-Joy do you receive the corect responses for public API methods?

**Comment by Geo-Joy** [comment]
@dutu responses are either 403 or their captcha page code.

**Comment by dutu** [comment]
Are you saying you never receive a corect response? Neither for public methods or private? 
I've been using this library for more than a year, wuthering apps running 24/7, and not encountered these errors. 
I ca try to help to figure out what's wrong in your case, but need more details.

**Comment by Geo-Joy** [comment]
@dutu 

OK then can you share your sample code - secret and key removed.

**Comment by dutu** [comment]
https://github.com/dutu/poloniex-api-node/blob/master/examples/rest-callback.js

**Comment by Geo-Joy** [comment]
![screen shot 2017-08-14 at 4 10 39 pm](https://user-images.githubusercontent.com/5595978/29268642-51e7b9a6-810b-11e7-8839-f55146cc2065.png)
@dutu plz let me know if iam doing it wrong.

**Comment by dutu** [comment]
If you access address below with a browser from the same machine, do you get JSON response? 
https://poloniex.com/public?command=returnTicker

**Comment by Geo-Joy** [comment]
@dutu 
![screen shot 2017-08-14 at 4 57 57 pm](https://user-images.githubusercontent.com/5595978/29269931-c60bdb04-8111-11e7-848b-48234351243c.png)
on completing the captcha i get the JSON response.

**Comment by g666nz** [comment]
having the exact same problem. And i was able to open up the page as well, after completing the catcha

**Comment by dutu** [comment]
The issue is caused by Poloniex or their cloudflare implementation and it looks that your ip address range has been flagged for restriction. 

I suggest you open a support ticket with poloniex and also provide them your external IP. 
Until Poloniex resolve the issue you can try using a vpn or host your application on a machine from different IP address range. 

If you would like to provide feedback with response from Poloniex, I can keep this issue open until response receive (although the issue is not related to this module)

**Comment by g666nz** [comment]
Thank you, i've been testing it on my desktop, i'll upload it to my vps and let you know if that worked.

**Comment by Geo-Joy** [comment]
@dutu tested it on digitalocean's instance with dedicated IP address. No luck yet!

**Comment by dutu** [comment]
As a first step, even before trying this module, you will the url below should give you a JSON response directly 
https://poloniex.com/public?command=returnTicker

After you have verified Poloniex is responding properly, go on and test with the module

**Comment by dinc334** [comment]
I have the same problem. try to use VPN - no changes, try to enable and disable 2fa and then create new api-key - no changes,  when open https://poloniex.com/public?command=returnTicker - I see JSON data, but any public methods from poloniex-api-node said this - Poloniex error 403: Forbidden
If i try console.log(poloniex) - Poloniex { _getPrivateHeaders: [Function] }

**Comment by dutu** [comment]
@dinc334, thanks for your feedback.
Just a note to start with: when calling public API methods, your account credentials are not used, hence settings on your account (such as API keys or 2FA) have no impact.

Can you please give additional details:
* are you opening https://poloniex.com/public?command=returnTicker from the same machine where you also use poloniex-api-node?
* is your machine behind a proxy?
* when opening https://poloniex.com/public?command=returnTicker, do you get a JSON response without using a VPN?
* do you get the JSON response directly or are your prompted first by the captcha?
* I'm not sure what you mean by "If i try console.log(poloniex) - Poloniex { _getPrivateHeaders: [Function] }". Can you give a more complete code example?

**Comment by dinc334** [comment]
- open from the same machine
- machine without proxy
-  https://poloniex.com/public?command=returnTicker - i get a JSON response without using VPN
- first by captcha
My code
let poloniex = new Poloniex(key,secret);
console.log(poloniex);
in console i see - Poloniex { _getPrivateHeaders: [Function] }

**Comment by dutu** [comment]
@dinc334 
* Please contact Poloniex support, **if you see a html page asking for security check when opening**  https://poloniex.com/public?command=returnTicker. Ask them to resolve the issue, as it seems Poloniex has flagged it for restriction. This page should give you a JSON result directly. You should also provide them your IP address, 

*  For code examples, please check https://github.com/dutu/poloniex-api-node/blob/master/examples/rest-callback.js

**Comment by mdarif** [comment]
@dinc334, any luck so far, have been facing the same issue since last month?

**Comment by dutu** [comment]
@mdarif it looks Poloniex has flagged your IP address (or address range) for restriction.
You'll need to report the issue to Poloniex by opening a support ticket and provide them **your** IP address.

**Comment by nguyenhoaibao** [comment]
@Geo-Joy Did you create this issue to the Poloniex's support team? How long did they process? I've created this issue one week ago, and no response until now :(.

**Comment by g666nz** [comment]
I processed the request on august 9th. Don't hold your breath and move on. Poloniex is not worth the effort. People are complaining about withdrawals not happening. And there customer support is literally non-existent. Don't waste your time.

**Comment by dutu** [comment]
I'm trying to figure out a way to bypass the captcha check...
Would you please help me find some info:

1. Open https://poloniex.com/public?command=returnTicker in your Chrome browser (should normally return a JSON)
2. When prompted for the security check (captch screen) complete the captcha in order to get the JSON response
3. In chrome look for the cookie `cf_clearance`. (to view the cookies go to `Developer Tools` by pressing `CTRL`+`Shift`+`i` -> `Application` tab -> `Cookies`)
4. Please confirm if this cookie exists and how long the expiration is.

We may be able to use this cookie to make the module skip the captcha check, but I'd need infor on the step 4 above.

Thank you!

**Comment by nguyenhoaibao** [comment]
@dutu in my laptop, the expires time of `cf_clearance` cookie is `2017-10-05T02:21:37.870Z`. If this time is in UTC, I think that (for me) the expiration is about 2 hours.

**Comment by DexHunter** [comment]
Hi! I also met this problem (I am in China). No luck even with VPN.

`cf_clearance` cookie is `2017-10-08T16:17:06.214Z`, so I guess the expiration time is about 1.5 hrs (in UTC).

**Comment by dutu** [comment]
Here is a workaround you can try in order to bypass the reCaptcha security check. 

Using version 1.6.1 or higher, set the `options.headers` parameter in the constructor, using your browsers's user-agent and `cf_clearance` cookie values.

Example:
```js
let headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
  'Cookie': 'cf_clearance=25a517254e54524fd5166817cbd6957ec43699fe-1507474839-1800'
}

let poloniex = new Poloniex({ options.headers: headers });
```
**You'd need to set your own values for the User-Agent and cf_clearance**.

* **To get your user-agent**:
 1. open the Console in your chrome browser and enter the command `navigator.userAgent`

* **To get your cf_clearance cookie**: 
 1. Open https://poloniex.com/public?command=returnTicker in your Chrome browser (should normally return a JSON)
2. When prompted for the security check (captcha screen) complete the captcha in order to get the JSON response
3. In chrome look for the cookie cf_clearance. (to view the cookies go to Developer Tools by pressing CTRL+Shift+i -> Application tab -> Cookies)

> The `cf_clearance` cookie gives you relatively short window of time to connect (see the cookie's expiration time). It's mean you can connect many times in this time frame, then you have to renew cookie (using your chrome browser). Depending on your application and the connection method you use (REST / WebSocket) the application may not need to reconnect often and you should be able to use use the API for long time (since the cookie is sent only when the connection is established). 
This method is of course very inconvenient but I'm afraid that's all we can do until Poloniex fixes the issue.

Feedback on the above is very welcome.

**Comment by nguyenhoaibao** [comment]
@dutu thanks for your solution. BTW is there any way to get this `cf_clearance` value automatically (via any method in the library) without opening the browser?

**Comment by dutu** [comment]
I'm afraid not. 
The security captcha for Poloniex is provided by CloudFlare and only way to pass the security check is by visiting the page with the browser and complete the captcha manually,. 

The cookie is stored in your browser, hence you need the browser to get it.

**Comment by ntuanphuc** [comment]
add your vps ip address in Poloniex api section

**Comment by giangvo1125** [comment]
@ntuanphuc add vào như thế nào vậy bạn ??? mình gọi vẫn trả về 403. Help mình.

**Comment by ntuanphuc** [comment]
@giangvo1125 https://poloniex.com/apiKeys --> Trusted IPs

**Comment by giangvo1125** [comment]
@ntuanphuc mình chọn option đó rồi nhưng gọi vẫn báo lỗi 
<img width="1437" alt="screen shot 2017-12-21 at 10 28 26 am" src="https://user-images.githubusercontent.com/11868731/34239412-cff583d0-e639-11e7-9adf-8546a7444fc8.png">

**Comment by ntuanphuc** [comment]
mình cũng bị trường hợp này, cũng add ip local vào mà vẫn bị 403, nhưng dùng qua vps thì ok nên mình dùng luôn trên vps

**Comment by giangvo1125** [comment]
@ntuanphuc dùng vps như thế nào vậy bạn ?

**Comment by ntuanphuc** [comment]
Bạn mua vps trên digitalocean chẳng hạn. Rồi code trên đó, add ip của vps vào poloniex là được.

**Comment by giangvo1125** [comment]
@ntuanphuc tks bạn

**Comment by wh1100717** [comment]
If anyone has been blocked with 403 code.
This solution by using shadowsocks may get this work

```javascript
import Agent from 'socks5-https-client/lib/Agent'
import Poloniex from 'poloniex-api-node'

class SocksPoloniex extends Poloniex {
  // To support shadow socks proxy
  _request (options, callback) {
    if (this.options.agentClass) {
      options.agentClass = this.options.agentClass
      options.agentOptions = this.options.agentOptions
    }
    return super._request(options, callback)
  }

  _requestPromised (options) {
    if (this.options.agentClass) {
      options.agentClass = this.options.agentClass
      options.agentOptions = this.options.agentOptions
    }
    return super._requestPromised(options)
  }
}

const options = {
  strictSSL: true,
  agentClass: Agent,
  agentOptions: {
    socksHost: '127.0.0.1', // Defaults to 'localhost'.
    socksPort: 1080 // Defaults to 1080.
  },
  socketTimeout: 15000
}

poloniex = new SocksPoloniex(options)

poloniex.returnTicker((err, ticker) => {
  if (err) {
    console.log(err.message)
  } else {
    console.log(ticker)
  }
})

```

**Comment by hunglee** [comment]
@wh1100717 using your method get this error
{ Error: connect ECONNREFUSED 127.0.0.1:1080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1080 }
undefined

**Comment by wh1100717** [comment]
@hunglee u should get a shadowsocks or some other socks5 proxy first

**Comment by guidoocean** [comment]
@wh1100717 when I try to use your code I have an error

`TypeError: Class constructor Poloniex cannot be invoked without 'new'
    at new SocksPoloniex (/mnt/Data/Work/poloitest/index.js:29:111)
    at Object.<anonymous> (/mnt/Data/Work/poloitest/index.js:33:12)
    at Module._compile (module.js:635:30)
    at loader (/mnt/Data/Work/poloitest/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/Data/Work/poloitest/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/mnt/Data/Work/poloitest/node_modules/babel-cli/lib/_babel-node.js:154:22)
`

**Comment by dutu** [comment]
Check @zymnytskiy's solution (#53) which is using `agent` option in the constructor

```js
const SocksProxyAgent = require('socks-proxy-agent')

const poloniex = new Poloniex('', '', {
  agent: new SocksProxyAgent('http://localhost:5000')
})
```

**Comment by dutu** [comment]
Here is an example that works and avoids the 403 error:

```js
const SocksProxyAgent = require('socks-proxy-agent');
const proxy = 'socks://192.210.170.171:1080';
let agent = new SocksProxyAgent(proxy);
let poloniex = new Poloniex('', '', {agent: agent});
```

**Comment by sy92th** [comment]
Please help me check this error! This still not working

Code
```
const Poloniex = require('poloniex-api-node');
const SocksProxyAgent = require('socks-proxy-agent');
const proxy = 'socks://159.174.11.160:1080';
const agent = new SocksProxyAgent(proxy);
const poloniex = new Poloniex('', '', {'agent': agent});
poloniex.returnTicker(function (err, ticker) {
    if (err) {
        console.log(err.message);
    } else {
        console.log(ticker);
    }
});
```
Data return:
`Failed to load https://poloniex.com/public?command=returnTicker: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
