### ISSUE TITLE
add params limit to history

### ISSUE THREAD

**Issue by steeply** [dutu/poloniex-api-node#24]
Please add an param 'limit' in method returnMyTradeHistory

> returnTradeHistory
> 
> You may optionally limit the number of entries returned using the "limit" parameter, up to a maximum of 10,000. If the "limit" parameter is not specified, no more than 500 entries will be returned.
> https://poloniex.com/support/api/

**Comment by dutu** [comment]
Parameter `limit` has been added to `returnMyTradeHistory` and `returnTradeHistory` methods. Thanks to @julesGoullee  for the PR!!

> Note the `limit` parameter is for now optional (i.e. the method can be called without it). This is for maintaining backwards compatibility. However, this option will be removed in the near and `limit` will be required when calling the methods (should be passed either as `null` or as an integer)

**Comment by steeply** [comment]
Excellent! Thank you!
