### ISSUE TITLE
SyntaxError: Unexpected token = with tradingApi.js:4

### ISSUE THREAD

**Issue by jinjasaisen** [dutu/poloniex-api-node#28]
im trying out the node api.
after npm i install, i would type
node my-rest.js
and returns the following error:

tradingApi.js:4
const create = (apiKey, secret, debug = false) => {
                                      ^

SyntaxError: Unexpected token =

**Comment by dutu** [comment]
@jinjasaisen the issue is in your `tradingApi.js` file; it's not related to poloniex-api-node module.

On line 4  in `tradingApi.js` change the code to
`const create = function (apiKey, secret, debug = false) => {`

Hope this helps.
