### ISSUE TITLE
WebSocket V2 - No messages coming through

### ISSUE THREAD

**Issue by jevdiego** [dutu/poloniex-api-node#29]
My code below is not receiving any BTC_ETH messages when I use version 2 as an option for 'openWebSocket'. 

I receive the console message "Poloniex WebSocket connection open", but never receive anything after subscribing to BTC_ETH. However, if I take away the version 2 option, these messages come through. What should be different here to receive messages when opening a web socket with version 2?

Thanks in advance
`
poloniex.subscribe('BTC_ETH');

    poloniex.on('message', (channelName, data, seq) => {
        console.log("Message Received");
        if (channelName === 'BTC_ETH') {
            console.log('order book and trade updates received for currency pair ', channelName);
            console.log('data sequence number is ', seq);
        }
    });

    poloniex.on('open', () => {
        console.log('Poloniex WebSocket connection open');
    });

    poloniex.on('close', (reason, details) => {
        console.log('Poloniex WebSocket connection disconnected');
    });

    poloniex.on('error', (error) => {
        console.log('An error has occured');
    });

    poloniex.openWebSocket({ version: 2 });
`

**Comment by dutu** [comment]
Thanks for reporting the issue. I'll have to push a small fix, in the meantime try calling `subscribe` after `openWebSocket`

**Comment by jevdiego** [comment]
OK great, thanks. Placed subscribe after and it's working.

Noticed that with both version 1 and 2, I received very old sequence numbers. If I pull the orderbook, I get a sequence number of 418148509 for example, but the stream gives me sequence numbers in the range of about 416881343. Is this common?

**Comment by kevflynn** [comment]
+1 - to clarify - it works if you subscribe only after on open succeeds
`poloniex.on('open', () => { // subscribe here })`

**Comment by dutu** [comment]
> Noticed that with both version 1 and 2, I received very old sequence numbers. If I pull the orderbook, I get a sequence number of 418148509 for example, but the stream gives me sequence numbers in the range of about 416881343. Is this common?

@jevdiego I have noticed the behavior you're describing on WAMP push API (version 1), and even reported it to Poloniex. There is no response to the support ticket yet (5 months later). Nevertheless, their WAMP API is known to have stability issues.

I have NOT noticed any delayed messages with the new WebSocket v2 API. Also to note, this is the version currently used on Poloniex website and I would expect it to be working well. Any way, if you experience any issues, I'd recommend that you open a support ticket with Poloniex.

**Comment by dutu** [comment]
this is now fixed in version 1.6.3

**Comment by jevdiego** [comment]
Ok great, thanks for the feedback dutu. Also, thanks for the fix!
