### ISSUE TITLE
Version 2 - no orderbook

### ISSUE THREAD

**Issue by jevdiego** [dutu/poloniex-api-node#31]
Hi,

The documentation says that when subscribing to a currency pair (version 2), the orderbook message type should be emitted:
"orderBook (v2 only)
Provides a snapshot of the order book for the subscribed currency pair. The message is emitted immediately after subscription to the currency pair is activated."

However, I never receive this type. Can anyone confirm that they are indeed getting this type. Code is shown below. Thanks

`poloniex.on('message', (channelName, data, seq) => {
        console.log("Message Received: ", channelName, seq);
        for (var i = 0; i < data.length; i++){
            console.log("type: ", data[i].type);
        }

        if (channelName === 'BTC_ETH') {

        }
    });

    poloniex.on('open', () => {
        console.log('Poloniex WebSocket connection open');

    });

    poloniex.on('close', (reason, details) => {
        console.log('Poloniex WebSocket connection disconnected:', reason, details);
    });

    poloniex.on('error', (error) => {
        console.log('An error has occured');
    });

    poloniex.openWebSocket({version: 2});

    poloniex.subscribe('BTC_ETH');`

**Comment by dutu** [comment]
Do you get the `open` message or any message at all?
Have you also tried to subscribe after `openWebSocket`
(see #29)

**Comment by jevdiego** [comment]
Hi dutu, yes I've tried subscribing after. I get all the other messages, orderbookmodify/remove etc, but never the 'orderbook' message. Posted this here, because I'm uncertain if this is an issue with the package or a Poloniex issue (assuming the latter). Was hoping someone could verify though if they were currently getting the 'orderbook' message when the currency pair is activated.

**Comment by ZhiweiWang** [comment]
The "orderBook" message is only trigged once after you subscribe new currency pair.
Like this:
```Poloniex WebSocket connection open
order book and trade updates received for currency pair USDT_BTC
data sequence number is 154792310
[ { type: 'orderBook', data: { asks: [Object], bids: [Object] } } ]```

Then you have to maintain your order book with following orderBookModify/Remove messages.

**Comment by dutu** [comment]
@jevdiego teh messages are being delivered in the right order and I can confirm the `orderBook` message **is**  received first as expected.
I have also added a test case to verify this and the test passes. 
https://github.com/dutu/poloniex-api-node/blob/master/test/integrationTestWebSocket2.js#L127
