### ISSUE TITLE
TypeError: Cannot read property 'currencyPair' of undefined

### ISSUE THREAD

**Issue by kevflynn** [dutu/poloniex-api-node#32]
Steps to reproduce:
1. Subscribe to ticker using poloniex.openWebSocket({ version: 2 });
2. Subcribe to BTC_ETH (not sure this step is 100% necessary)
3. Run - I see this error about 50% of the time.

/node_modules/poloniex-api-node/lib/poloniex.js:603
                currencyPair: markets.byID[rawData[0]].currencyPair,
                                                      ^

UPDATE *** -always happens when rawData[0] = 200

**Comment by kevflynn** [comment]
PR #33 fixes this issue

**Comment by uliporeggia** [comment]
:+1:
Same here.

**Comment by n0mad01** [comment]
this is because poloniex-api-node/lib/markets.js does not contain any market number > 199

i've added 2 pull requests which fix that:
fix: TypeError: Cannot read property 'currencyPair' of undefined #37
and:
update markets.js #38

**Comment by Dinfyru** [comment]
+1

**Comment by dutu** [comment]
this is now fixed with v1.6.4

**Comment by uliporeggia** [comment]
I still with the problem after updating to `^1.6.4`.

```
/home/ubuntu/spread-api/node_modules/poloniex-api-node/lib/poloniex.js:605
                currencyPair: markets.byID[rawData[0]].currencyPair,
                                                       ^

TypeError: Cannot read property 'currencyPair' of undefined
    at WebSocket.ws.onmessage (/home/ubuntu/spread-api/node_modules/poloniex-api-node/lib/poloniex.js:605:56)
```

I made a cheap solution by adding some `or`s at [L600](https://github.com/dutu/poloniex-api-node/blob/master/lib/poloniex.js#L600) but I think it does not justify a PR

```
if (!rawData || !rawData[0] || !markets.byID[rawData[0]]) {
    return;
}
```

**Comment by Dinfyru** [comment]
same issue 1.6.4
```
/home/ubuntu/workspace/node_modules/poloniex-api-node/lib/poloniex.js:605
                currencyPair: markets.byID[rawData[0]].currencyPair,
```

**Comment by dutu** [comment]
Please see new v1.6.5
([CHANGELOG](https://github.com/dutu/poloniex-api-node/blob/master/CHANGELOG.md))

**Comment by Dinfyru** [comment]
Looks good.

**Comment by uliporeggia** [comment]
Working perfect for me! Thanks.
