### ISSUE TITLE
ws2 example not working 

### ISSUE THREAD

**Issue by tesla1060** [dutu/poloniex-api-node#44]
Hi,
 `ws2.js` after printing out `Poloniex WebSocket connection open`, no real time update comes back.

**Comment by BrandonCopley** [comment]
There is a typo here:

    if (channelName === 'BTC_ETC') {
      console.log(`order book and trade updates received for currency pair ${channelName}`);
      console.log(`data sequence number is ${seq}`);
    }

channelName should be BTC_ETH

**Comment by dutu** [comment]
example file has been updated
