### ISSUE TITLE
Is there a private websocket channel for orders placed/trades executed?

### ISSUE THREAD

**Issue by magicdude4eva** [dutu/poloniex-api-node#49]
As the title says: Does Websocket v2 support trade/order updates for my own orders and if so, does anyone know the channel names?

**Comment by dutu** [comment]
There is no support for private API methods for Websocket v2.
Websocket v2 is not documented by Poloniex nor officially released, and also there are no examples of any private API calls

**Comment by magicdude4eva** [comment]
Thanks for that info. I also reached out to Poloniex and received no concrete feedback. I will close this question.
