### ISSUE TITLE
Error response needs to be stringified

### ISSUE THREAD

**Issue by asdobson** [dutu/poloniex-api-node#5]
In poloniex.js Line 63: 
    ``err =  new Error(`Poloniex error ${response.statusCode}: ${response.body}` );``
should be:
    ``err =  new Error(`Poloniex error ${response.statusCode}: ${JSON.stringify(response.body) }`);``

Same with line 71, otherwise error output is `[object Object]` rather than ` {"error":"errorcode."}`

**Comment by dutu** [comment]
Thank you for reporting the issue. It looks that Poloniex has recently changed the way they return the error detail.
This is now fixed in v1.0.1
