### ISSUE TITLE
WebSocket never calls newTrade

### ISSUE THREAD

**Issue by yusufozcan** [dutu/poloniex-api-node#50]
I am subscribing USDT_BTC market, I get the ordermodify and orderremove messages but not newTrade message.

**Comment by Eli-Goldberg** [comment]
Same thing here, why is the issue closed?
USDT_BTC always produces orderBookModify and orderBookRemove but no newTrade.
Could anyone help out? :)

**Comment by Eli-Goldberg** [comment]
I apologise, it was my code.
this project works great.
This can be closed.
