### ISSUE TITLE
Nonce format changed

### ISSUE THREAD

**Issue by thesun2003** [dutu/poloniex-api-node#52]
Poloniex error 422: . Nonce must be greater than 1515827307860912000. You provided 151582954164400.

I believe that new format is nonce(20) instead of the nonce(16).

Could you please fix it?

**Comment by dutu** [comment]
Poloniex only requires that the nonce is an ever increasing number. Length of the nonce is not important as long as it's a number bigger than the previous valid nonce.
To get your problem fixed, generate a new api key. Make sure you only use that API key for the bot and nowhere else.
