### ISSUE TITLE
returnDepositAddresses() swaps address tag with address

### ISSUE THREAD

**Issue by willadamskeane** [dutu/poloniex-api-node#54]
When calling returnDepositAddresses(), for currencies that use address tags like Stellar (STR), only the tag is being returned rather than both the tag and the address.

Also, I'm not sure if withdraw() supports passing through an address tag? If so, it is not documented.

**Comment by dutu** [comment]
This API wrapper module is passing the API responses as received from Poloniex server, without alteration.
I suggest, for the question above, you open a support ticket with Poloniex.

**Comment by willadamskeane** [comment]
What about passing the address tag (payment id) to withdraw()? I believe it is an optional argument supported by the Poloniex api but does not seem to be supported by this library.

**Comment by dutu** [comment]
I have updated the module (version 1.8.1) and parameter `paymentId` is now supported for method `withdraw`.
