### ISSUE TITLE
returnLendingHistory end param forces empty return

### ISSUE THREAD

**Issue by negedzuregal** [dutu/poloniex-api-node#55]
When using returnLendingHistory with the end parameter higher than the last lending record the api returns an empty array.

For example in my account the last closed lending is at 10/06/2017 but if I try to pass as the end parameter 11/06/2017 it all of a sudden returns an empty array

any idea why?

**Comment by dutu** [comment]
Check the time format in the example here #13

**Comment by negedzuregal** [comment]
I've used exactly that format... problem is changing the end param for any date which is after my last lending. Doing that returns an empty array.

**Comment by dutu** [comment]
@negedzuregal, I could reproduce the issue and I can confirm that setting `end` parameter to a time past the current time results `returnLendingHistory` returning an empty array.

This is definitely an issue on Poloniex side, not this module. It'll be good if you could report it to Poloniex support.

l'll keep this issue open here for other users to be aware of it. I'd appreciate if you can give feedback in case Poloniex support responds.

**Comment by dutu** [comment]
I have reported the issue to Poloniex support on 30 Jan.
Awaiting their response...

**Comment by sph34r** [comment]
@negedzuregal @dutu, I too had the same issues. It seems to fail when the search's end parameter is about 30 days after the last loan/entry and I think this may be on purpose. To be sure, you could iterate in 30 day segments or so.

**Comment by rmnoff** [comment]
Poloniex is definitely restricting access to the previous history.
Maybe they are doing it because of security reasons.

**Comment by dutu** [comment]
Poloniex support has indicated that the issue is resolved and I have tested successfully
