### ISSUE TITLE
returnTicker method sometimes produce fatal error and exit.

### ISSUE THREAD

**Issue by MatveiFisenko** [dutu/poloniex-api-node#57]
I use poloniex-api-node to subscribe to ticker events using openWebSocket({ version: 2 }) method.

From time to time node app exits after such error:
```
node[15508]: /app/node_modules/poloniex-api-node/lib/poloniex.js:601 
node[15508]: this.ws.send('.') 
node[15508]: ^ 
node[15508]: TypeError: Cannot read property 'send' of null
node[15508]: at Timeout.ws.keepAliveId.setInterval [as _onTimeout] (/app/node_modules/poloniex-api-node/lib/poloniex.js:601:24) 
node[15508]: at ontimeout (timers.js:469:11) 
node[15508]: at tryOnTimeout (timers.js:304:5) 
node[15508]: at Timer.listOnTimeout (timers.js:264:5)
```

Current workaround is to restart node app after every exit.

**Comment by dutu** [comment]
@MatveiFisenko do you get a close event around that time as well?

**Comment by dutu** [comment]
would you please use version 1.8.2 and let me know if it fixes the issue

**Comment by dutu** [comment]
I'm closing this one, if any other issues, you are welcome to report again

**Comment by MatveiFisenko** [comment]
@dutu, no close event did not fire near this time.
I'll use 1.8.2 for some time and return if issue will happen.
