### ISSUE TITLE
moveOrder always throws error: Invalid currency pair.

### ISSUE THREAD

**Issue by bennytjia** [dutu/poloniex-api-node#58]
```
_poloniex.moveOrder(order_number, rate, amount).then((msg) => {
    console.log(msg);
}).catch(err => console.log(err)); //this line throws error "Invalid currency pair".
```
I'm currently having a hard time debugging this part of the code, which is currently breaking my whole application because of it throwing an "invalid currency pair" error. I'm not sure why that is happening, and not aware of additional parameter of currency pair string as a missing required parameter I assume causing this error.

Error message:
```
Error: Invalid currency pair.
    at Request._callback (/Users/user_1/person/myapp/node_modules/poloniex-api-node/lib/poloniex.js:183:17)
    at Request.self.callback (/Users/user_1/person/myapp/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/user_1/person/myapp/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/user_1/person/myapp/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

This part also never caused issue when I was testing out last week, where my app ran just fine. This seems to be a recent issue (happening since yesterday). Please advise. thanks.

**Comment by bennytjia** [comment]
@dutu ?

**Comment by theonlyfox** [comment]
Could be a while before he responds.  What pair was the trade using?  moveOrder isn't concerned with pairs, but if the order is on a locked, frozen, or discontinued pair on Polo you might get this error as that error message is sent from Polo.

**Comment by bennytjia** [comment]
It was BTC_ETH. I'm not sure what a locked/frozen order means? 

When an order is placed through a buy/sell REST call, the response will give you the order number. If what you meant was a cancel REST call is executed before any of that happens (due to probably some asynchronous bug in the code), then what I noticed was that the error code was different. I remember it was something similar to "invalid or undefined order number".

**Comment by theonlyfox** [comment]
cool beans.  What  I meant by locked and frozen is what the Exchange does to halt trading on a coin pair either because of a technical issue with the trade engine, an attack on the trade engine, or the move to de-list a pair.  Polo's error messages are not very helpful, instead of invalid pair it should have returned an invalid order number. :D
