### ISSUE TITLE
returnTradeHIstory is returning an empty array

### ISSUE THREAD

**Issue by theonlyfox** [dutu/poloniex-api-node#59]
Final Edit: ok this is a timing issue.  I pulled the header from the request response and dropped that into a browser.  At first I got an empty page.  I went to compare the header href to the one below to see what was different.  The only difference is the position of the command tag.  When I went back to the web page it had populated with data.  At any rate, here is the header pulled from the response in the API.

> {"statusCode":200,"body":[],"headers":{"date":"Mon, 05 Feb 2018 06:11:18 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"keep-alive","set-cookie":["__cfduid=d62fed55e290841d93d9986017a75f20c1517811078; expires=Tue, 05-Feb-19 06:11:18 GMT; path=/; domain=.poloniex.com; HttpOnly"],"access-control-allow-origin":"*","access-control-allow-methods":"GET","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","server":"cloudflare","cf-ray":"3e83b6294f0b58a9-DFW"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"poloniex.com","port":null,"hostname":"poloniex.com","hash":null,"search":"?currencyPair=USDT_BTC&start=1517811078&end=1517831078&limit=300&command=returnTradeHistory","query":"currencyPair=USDT_BTC&start=1517811078&end=1517831078&limit=300&command=returnTradeHistory","pathname":"/public","path":"/public?currencyPair=USDT_BTC&start=1517811078&end=1517831078&limit=300&command=returnTradeHistory","href":"https://poloniex.com/public?currencyPair=USDT_BTC&start=1517811078&end=1517831078&limit=300&command=returnTradeHistory"},"method":"GET","headers":{"User-Agent":"poloniex-api-node 1.6.5","Connection":"keep-alive","accept":"application/json"}}}

edit:
 Tracking this deeper.  The API is seeing the right options, the following is pulled from the request() on options.qt  : 
{"currencyPair":"USDT_BTC","start":1517809825,"end":1517829825,"limit":300,"command":"returnTradeHistory"}

You can put those directly into the the web request html and they work.   I print the body body before the callback in request() just to see if we get anything back there and it's the same empty array.   Could this be a timing issue where the API isn't waiting long enough for a full response from the web request?

edit: 
I know Polo is working just tried a web request and it worked:  [https://poloniex.com/public?command=returnTradeHistory&currencyPair=USDT_BTC&start=1517808279&end=1517828279](https://poloniex.com/public?command=returnTradeHistory&currencyPair=USDT_BTC&start=1517808279&end=1517828279 )

original:
I have tried increasing the start and stop times and limit to no avail.  It managed to return 2 completed orders on one run but nothing since.  Has Polo moved all of its trade history to a stream?  I haven't tried subscribing to a stream yet.  Code below in case you see if I'm doing something wrong.
`
function PullTradeHistory(pair, callback){
	var startTime = ~~(Date.now()/1000);
	var endTime = startTime + 2000000;

	console.log(startTime);
	console.log(endTime);
	console.log(pair);
	poloniex.returnTradeHistory(pair, startTime, endTime, 300, function(err, completedTrades){
			if(err){
				//handle error
			}
			else{
					console.log("getting completed trades back");
					console.log(JSON.stringify(completedTrades));
					console.log(JSON.stringify(err));
				 callback(err, completedTrades);
			 }
		});

};
`

output:
1517807472
1519807472
USDT_BTC
getting completed trades back
[ ]
null

**Comment by theonlyfox** [comment]
Any insights on this.  Ive tried watching the stream even to see if I can catch any data being returned after the header arrives and returns, but Im very green with node and not sure if I'm doing it right.

**Comment by dutu** [comment]
In your example `startTime` is the current time and `endTime` a future time.

Also if I look at the HTTP request you have shown, the `startTime = 1517811078` is the same as the time of the API request and `endTime` a future time. Is not surprising you don't get any trades.

Try with both `startTime` and `endTime` as past time values, or at least only `endTime` should be the current time.

**Comment by ryanfalzon** [comment]
If you have 20,000 transactions to retrieve, and the maximum number you can retrieve with one call is 10,000, how do I get the other 10,000 if there is no offset parameter?

**Comment by dutu** [comment]
Use `start` and `end` parameters

**Comment by ryanfalzon** [comment]
> Use `start` and `end` parameters

I tried setting the endDate of the next call to the last transaction's date but I have missing transaction in between. Have you ever experienced this?
