### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by CraigglesO** [dutu/poloniex-api-node#6]
`error Error: SSL Error: https://poloniex.com/public?command=returnCurrencies does not support SSL`

I've seen other libraries comment on this error. Any suggestions to fix?

**Comment by dutu** [comment]
Are you getting the error with this library?

Would you please copy&paste the exact error message returned?

**Comment by dutu** [comment]
@CraigglesO I have not seen the SSL error with this module. If you're getting the error Would you please copy&paste the exact error message returned, or else I should close this issue. Thanks

**Comment by CraigglesO** [comment]
Sorry friend! Been busy:
![alt-img](https://www.dropbox.com/s/ushtof4hwjmpa11/Screen%20Shot%202017-04-15%20at%203.40.53%20PM.png?dl=1)

You can ignore the parity log/ react comments... 


To be clear I did some tests and if I use strictly node, success. No errors.

In the browser, however...there is an issue -_-

I remember seeing another NPM module that uses Poloniex that said they had a "turn ssh off flag" for probably this exact purpose.

**Comment by dutu** [comment]
@CraigglesO, this library is build for node.js, as mentioned in the description. It uses module `request`, I don't see that `request` has been tested for browsers. 

Let me know if there is a need for similar library for browsers, and I would consider releasing one (and eventually merge the two)

**Comment by CraigglesO** [comment]
Ok. -_- Thanks for your help! 👍

**Comment by dutu** [comment]
I will close this for now (since the library was initially intended for node.js only) and will add browser support shortly. Will let you know when done
