### ISSUE TITLE
Socket Closed

### ISSUE THREAD

**Issue by nmquaan** [dutu/poloniex-api-node#62]
Hi everyone,
I clone this example on local and run it after that I have to receive an error "Socket Closed."
`const Poloniex = require ('poloniex-api-node');
const SocksProxyAgent = require('socks-proxy-agent');
const proxy = 'socks://localhost:1080';
let agent = new SocksProxyAgent(proxy);
let poloniex = new Poloniex('', '', {agent: agent});

poloniex.subscribe('ticker');
poloniex.subscribe('BTC_ETH');

poloniex.on('message', (channelName, data, seq) => {
    if (channelName === 'ticker') {
        console.log(`Ticker: ${JSON.stringify(data)}`);
    }

    if (channelName === 'BTC_ETH') {
        console.log(`order book and trade updates received for currency pair ${channelName}`);
        console.log(`data sequence number is ${seq}`);
    }
});

poloniex.on('open', () => {
    console.log(`Poloniex WebSocket connection open`);
});

poloniex.on('close', (reason, details) => {
    console.log(`Poloniex WebSocket connection disconnected`);
});

poloniex.on('error', (error) => {
    console.log(`An error has occur: ${error}`);
});

poloniex.openWebSocket({ version: 2 });`
Please help me check this error!
Thanks for the support!!!

**Comment by nmquaan** [comment]
@dutu, please help me!!!
Thanks for the support!

**Comment by dutu** [comment]
For example above you'd need to have a proxy installed on your localhost,

Alternatively, use a free socks proxy (search on the internet). 
Also check the example [here](https://github.com/dutu/poloniex-api-node/issues/20#issuecomment-364072493) (with `proxy = 'socks://192.210.170.171:1080'`), which worked for me.

**Comment by nmquaan** [comment]
Thanks for the support @dutu !!!
I followed this example [https://github.com/dutu/poloniex-api-node/issues/20#issuecomment-364072493](url) but not resolve this issue.

**Comment by dutu** [comment]
test this
`proxy = 'socks://159.174.11.160:1080'`

**Comment by nmquaan** [comment]
@dutu This proxy worked!
Thanks!

**Comment by nmquaan** [comment]
@dutu Thanks for the support so much but I want to ask "How to keep alive sock proxy?".
After an interval, The proxy free has to die after that WebSocket received a error 

> An error has occur: Error: read ECONNRESET
Poloniex WebSocket connection disconnected

**Comment by dutu** [comment]
The library has implemented a keepAlive functionality, which sends a message every 60 second.
I suggest you handle connection resets in your application in order to reconnect when needed.

**Comment by nmquaan** [comment]
I understood I want to have a sock proxy work long time not die after interval time. Please suggest to me.
Thanks for the support @dutu

**Comment by sy92th** [comment]
Please help me check this error! This still not working

Code
```
const Poloniex = require('poloniex-api-node');
const SocksProxyAgent = require('socks-proxy-agent');
const proxy = 'socks://159.174.11.160:1080';
const agent = new SocksProxyAgent(proxy);
const poloniex = new Poloniex('', '', {'agent': agent});
poloniex.subscribe('ticker');
poloniex.subscribe('BTC_ETH');

poloniex.on('message', (channelName, data, seq) => {
    if (channelName === 'ticker') {
        console.log(Ticker: ${JSON.stringify(data)});
    }

    if (channelName === 'BTC_ETH') {
        console.log(`order book and trade updates received for currency pair ${channelName}`);
        console.log(`data sequence number is ${seq}`);
    }
});

poloniex.on('open', () => {
    console.log('Poloniex WebSocket connection open');
});
poloniex.on('close', (reason, details) => {
    console.log('Poloniex WebSocket connection disconnected');
});
poloniex.on('error', (error) => {
    console.log(error);
});
poloniex.openWebSocket({ version: 2 });`
```
Error:
`Failed to load https://poloniex.com/public?command=returnTicker: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by nmquaan** [comment]
@sy92th , This example still work I think sock proxy has died.
Please try again with "101.78.241.74:1080" or "103.10.52.83:30331"

**Comment by sy92th** [comment]
I try with new proxy but still not work

**Comment by sy92th** [comment]
For now I use "Hotspot Shield VPN Free Proxy" in Chrome and "returnTicker" worked
But Websocket has error:

```
GET https://api2.poloniex.com/ 400

Failed to load https://api2.poloniex.com/: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:9000' is therefore not allowed access. 
The response had HTTP status code 400. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by rmnoff** [comment]
@sy92th the issue hides in your local machine, which sends no Access-Control-Allow-Origin header to the server via WebSocket. Try to set CORS (via cors module).

**Comment by dutu** [comment]
@sy92th, it looks you are using the module in the browser. 
The module is intended to be used and has only been tested on node.js.
If you still have troubles on node.js, please open a new issue as this was originally opened for "socket closed"
