### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by akkishay** [dutu/poloniex-api-node#63]
When I try to run the ws2.js it gives 403 forbidden error.

where I am getting wrong?

**Comment by dutu** [comment]
Check [#20](https://github.com/dutu/poloniex-api-node/issues/20#issuecomment-322164424) and see if it relates to your problem.

**Comment by akkishay** [comment]
I want to use your scripts without sock proxies. how could I do this?

**Comment by dutu** [comment]
@akkishay, have a look at the issue I mentioned, you need to figure out if your IP address is restricted by cloudflare from accessing Poloniex.

If you IP is restricted you can use another machine, a VPN, a sock proxy, or report the issue to Poloniex.

**Comment by akkishay** [comment]
Does sock proxy dies after a particular amount of time?

**Comment by dutu** [comment]
Depends on what sock proxy you use

**Comment by akkishay** [comment]
any example which dont die?
