### ISSUE TITLE
Poloniex API location?

### ISSUE THREAD

**Issue by serzhiio** [dutu/poloniex-api-node#69]
Trying to use your project for HFT.
Do you know where is Poloniex API server located?

**Comment by dutu** [comment]
The API server is `poloniex.com`
Use https://www.iplocation.net/ to find the location

**Comment by redstrike** [comment]
**Ashburn, VA, United States** - (IAD)

I was finding this too. Finally, I found it here: https://docs.poloniex.com/#minimize-latency
