### ISSUE TITLE
Error: WebSocket is not open

### ISSUE THREAD

**Issue by toffick** [dutu/poloniex-api-node#71]
Help plz with a ws. What can you say about the following error and how to catch it? Sometimes it crashed my process.
` Error: WebSocket is not open: readyState 0 (CONNECTING)
 |     at WebSocket.send (/home/server/node_modules/ws/lib/websocket.js:314:19)
 |     at Timeout.ws.keepAliveId.setInterval [as _onTimeout] (/home/server/node_modules/poloniex-api-node/lib/poloniex.js:619:25)
 |     at ontimeout (timers.js:482:11)
 |     at tryOnTimeout (timers.js:317:5)
 |     at Timer.listOnTimeout (timers.js:277:5)
`

**Comment by dutu** [comment]
Please reopen this issue if error is seen again in v2.0.0
