### ISSUE TITLE
Websocket disconnets randomly

### ISSUE THREAD

**Issue by gogosb** [dutu/poloniex-api-node#73]
I use the websocket API, but the connection close randomly:
Poloniex WebSocket connection disconnected
  {
  "reason": "CloudFlare WebSocket proxy restarting",
  "code": 1001
}
Could you help me to fix the problem?

**Comment by dutu** [comment]
To which channel(s) are you subscribing and approximately after how long time are you getting disconnected?

**Comment by gogosb** [comment]
I subscribe the ticker and all of the 'BTC_*' channels of Poloniex.  Now I handle the situation by opening the websocket again when close event is emitted. 


var init = () => {
    poloniex.openWebSocket();
    poloniex.subscribe('ticker');
    
	poloniex.on('message', (channelName, dataSet) => {
		if (channelName === 'ticker') {
			if (dataSet.currencyPair.indexOf('BTC_') > -1 || dataSet.currencyPair === 'USDC_BTC') {
                if (ticker[dataSet.currencyPair] === undefined) {
                    console.log(`Subscribing to ${dataSet.currencyPair} currency-pair.`)
                    poloniex.subscribe(dataSet.currencyPair);
                }
			}
		}
	});
    poloniex.on('open', () => {
        console.log(`  Poloniex WebSocket connection open`);
    });
       
    poloniex.on('close', (reason, details) => {
        console.log(`  Poloniex WebSocket connection disconnected`);
        console.log(`  ${JSON.stringify(reason, undefined, 2)}`);
        console.log(`  ${details}`);
        poloniex.openWebSocket();
    });
       
    poloniex.on('error', (error) => {
        console.log(`  An error has occured`);
        console.log(`  ${error}`);
        poloniex.closeWebSocket();
        poloniex.openWebSocket();

    });

    poloniex.on('heartbeat', () => {
        console.log(`  Poloniex WebSocket heartbeat event`);
    });
}

**Comment by gogosb** [comment]
Now I got another reason code:
Poloniex WebSocket connection disconnected
  {
  "reason": "",
  "code": 1006
}

**Comment by dutu** [comment]
I can confirm the WebSocket closes occasionally with reason "CloudFlare WebSocket proxy restarting".
It looks the disconnect is from Poloniex servers and the module is behaving as expected.

You may want to raise a ticket with Poloniex support.

**Comment by dutu** [comment]
Here is the answer from Poloniex support regarding the issue:

> Thanks for reaching out.
>
> In regards to the error you are experiencing, when CloudFlare releases that code it means that the websocket connections are terminated.
>
>As a workaround, we would suggest you to build in some reconnection strategy in the event a connection closes.
>
>Please let us know if you have any other questions!
>
>Best, 
>Poloniex Support Team

**Comment by gogosb** [comment]
Hi,

Thank you for your help.  So I used the recommended workaround - reopen the socket.  :)

Regards,
Barnabas
