### ISSUE TITLE
Stop / Limit Orders 

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [dutu/poloniex-api-node#74]
Hi guys, congrats for the good job done here. Been using your library for a while for some amateur trials. Now I am trying to place a Stop Limit order and realize that is not supported here and probably not at Poloniex API either. Can you please confirm there is no way to place one using some wired combination of parameters on the current Buy or Sell command? Is it simply not possible?

**Comment by dutu** [comment]
@Luis-Fernando-Molina Poloniex doesn't provide an API for placing a stop-limit order.
https://docs.poloniex.com/#buy
However, you can achieve this by programming your application (monitor the ticker and use combination of buy/sell and cancel order when specific conditions are fulfilled)

**Comment by Luis-Fernando-Molina** [comment]
Thanks @dutu ! It is crystal clear now. Cheers!
