### ISSUE TITLE
Poloniex error #422

### ISSUE THREAD

**Issue by nsnikolaev** [dutu/poloniex-api-node#76]
I have: "Poloniex error 422: . Nonce must be greater than 1573038171160165. You provided 157719741402400."

But!
1573038171160165 - is 16 digits
157719741402400 - is 15 digits

What this?

**Comment by dutu** [comment]
You have probably previously used another library that was generating a 16 digit nonce.
To fix the issue generate and use new API key.

**Comment by nsnikolaev** [comment]
Fixed! Thanks you!!!
