### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by Filip3Dev** [dutu/poloniex-api-node#9]
i don't know if it's real a issue or i'm doing something wrong but when i try to call a private method i get a cors error
![captura de tela de 2017-04-29 17-50-25](https://cloud.githubusercontent.com/assets/19575298/25558784/63378890-2d04-11e7-8dd8-1a2321c9db0a.png)

**Comment by dutu** [comment]
Are you using the module in a browser?

**Comment by Filip3Dev** [comment]
no, i'm using this way...
![captura de tela de 2017-04-29 17-58-24](https://cloud.githubusercontent.com/assets/19575298/25558850/857d61bc-2d05-11e7-8226-c885d7bb507d.png)

**Comment by dutu** [comment]
@Filip3Dev, this library was tested as node.js module andf the description states it is a node.js library; you are using it in browser/client. 
The library is using `request` module and I cannot see `request` has been tested in browser either. I will release and test the library for the browser in one of the next revisions.

**Comment by bernatfortet** [comment]
@dutu Any updates on the library for the browser?

Thanks
