### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by pal9000i** [dutu/poloniex-api-node#90]
I've tried several solutions, but doesn't work. Is there a version that doesn't use ESM but supports the latest Poloniex API version?

**Comment by pal9000i** [comment]
Will be super grateful!

**Comment by pal9000i** [comment]
Error: Cannot find module 'path/node_modules/poloniex-api-node/dist/cjs/poloniex.js'

**Comment by dutu** [comment]
I fixed fix `exports` entry for CommonJS in `package.json` and added the tests to cover such mistakes in the file. Have released v3.1.1

**Comment by pal9000i** [comment]
Thanks a lot for the super quick update. Seems to be working now! 🥳
