### ISSUE TITLE
Problems canceling orders

### ISSUE THREAD

**Issue by GuiSchet** [dutu/poloniex-api-node#93]
Hello,

I tried the methods: cancelOrders, cancelBatchOrders, CancelAllOrders. But I cant find the way to make it...

I tried using:
only order id, list of id's, etc...

This is not a problem of Keys, because i made orders without any problems. I leave some function examples that worked:

const allMarkets = async () => {
    let markets = poloniex.getSymbols({});
    return markets;
};

const getOrderBook = async (simboloMercado) => {
    let orders = await poloniex.getOrderBook({symbol: simboloMercado, limit: 100});
    return orders; 
};

const getBalance = async () => {
    let balance = await poloniex.getAccountsBalances({accountType: 'SPOT'});
    let data = await balance[0].balances;
    return await data;
};

const getPrecioHisto = async (simboloMercado) => {
    let candles = poloniex.getCandles({symbol: simboloMercado, interval: 'DAY_1', limit: 10});
    return candles;
};

const ordenCompra = async (simboloMercado, cantidad, lado, precio) => {
    let orden = poloniex.createOrder({
        'symbol': simboloMercado,
        'type': 'LIMIT',
        'quantity': cantidad,
        'side': lado,
        'price': precio,
    });
    return orden;
};

const openOrders = async () => {
    let openOrders = await poloniex.getOpenOrders();
    return openOrders;
};

const getOpenOrders = async () => {
    let open = await poloniex.getOpenOrders();
    return open;
};

if someone can help me with a cancelorder example i'll be really greatfull!

**Comment by dutu** [comment]
Please try newly released v3.1.3 and see if it works

**Comment by GuiSchet** [comment]
Hi,
It's solved! 
I tried cancelAllOrders({symbols: ['LTC_BTC', 'XXX_BTC']}) and cancelOrder({id: '121212121'})

The two methods are working ok. Thanks, great wrapper, if sometime you need colaborators to add examples, usecases or docs send me a notification.
